import re
import string

FORBIDDEN_SHORTS = ['files']
AUTO_GENERATE_SHORT_MAX_LENGTH = 6
ALLOWED_CHARS = string.ascii_letters + string.digits
SHORT_REG_EXPR = fr'^[{re.escape(ALLOWED_CHARS)}]+$'
MAX_SHORT_GENERATION_ATTEMPTS = 10
ORIGINAL_LINK_MAX_LENGTH = 2048
USER_SHORT_MAX_LENGTH = 16
REDIRECT_VIEW = 'redirect_view'
