import string

FORBIDDEN_SHORT = 'files'
CUSTUM_ID_MAX_LENGTH = 6
ALLOWED_CHARS = string.ascii_letters + string.digits
REG_EXPR = r'^[A-Za-z0-9]+$'
MAX_SHORT_GENERATION_ATTEMPTS = 10
ORIGINAL_LINK_MAX_LENGTH = 2048
USER_CUSTOM_ID_MAX_LENGTH = 16